name: awali

channels:
- conda-forge

dependencies:
- python=3.10
- cython=3.0.8
- jupyterlab=4.1.3
- cxx-compiler=1.7.0
- cmake=3.28.3
- graphviz=9.0.0

# Needed for CORA
- ncurses=6.4

# Needed for documentation
#- doxygen
#- nbconvert
