name: awali

channels:
- conda-forge

dependencies:
- python=3.12
- cython
- jupyterlab
- cxx-compiler
- cmake
- graphviz

# Needed for CORA
- ncurses

# Needed for documentation
- doxygen
- nbconvert
