#!/bin/sh
VERSION=awali-all-v1.0.0-190215
FILE=$VERSION.tgz
URL="http://files.vaucanson-project.org/tarballs/$FILE"

wget $URL
tar xf $FILE 
cd $VERSION
mkdir _build
cd _build
cmake ..
make
make b
#sudo make install
